services:
  # ─── Auth Database ─────────────────────────────────────────
  db_auth:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_AUTH_DATABASE}
    volumes:
      - db-auth-data:/var/lib/mysql
    healthcheck:
      test:     ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout:  3s
      retries:  10

  # ─── Store Database ────────────────────────────────────────
  db_store:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_STORE_DATABASE}
    volumes:
      - db-store-data:/var/lib/mysql
    healthcheck:
      test:     ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout:  3s
      retries:  10

  # ─── Auth Service ──────────────────────────────────────────
  auth:
    build: ./backend/auth-service
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db_auth
      - MYSQL_DATABASE=${MYSQL_AUTH_DATABASE}
      - FLASK_ENV=production
    ports:
      - "5001:5000"
    depends_on:
      db_auth:
        condition: service_healthy

  # ─── Store Service ─────────────────────────────────────────
  store:
    build: ./backend/store-service
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db_store
      - MYSQL_DATABASE=${MYSQL_STORE_DATABASE}
      - FLASK_ENV=production
    ports:
      - "5002:5000"
    depends_on:
      db_store:
        condition: service_healthy

volumes:
  db-auth-data:
  db-store-data:
